
set nocompatible                 " choose no compatibility with legacy vi
call pathogen#infect('bundle/{}')
syntax enable
set encoding=utf-8
set showcmd                     " display incomplete commands
filetype plugin indent on       " load file type plugins + indentation

"" Whitespace
set nowrap                      " don't wrap lines
set tabstop=2 shiftwidth=2      " a tab is two spaces (or set this to 4)
set expandtab                   " use spaces, not tabs (optional)
set backspace=indent,eol,start  " backspace through everything in insert mode

abbr g_> <Place name=""><Action type="" keyword=""></Action></Place>
"" Searching
set hlsearch                    " highlight matches
set incsearch                   " incremental searching
set ignorecase                  " searches are case insensitive...
set smartcase                   " ... unless they contain at least one capital letter
set nu
let mapleader = ","
let @x='^Yp:s/</<\//'

nmap <Leader>x = @x

function XmlT() 
  :s/\(.*\)#/<\1'/
  :s/=\(.*\)\?/ "\1" /

 
endfunction
